version: '3.7'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  vscode:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      # SSH directory for Linux, OSX and WSL
      # - ~/.ssh:/root/.ssh:z
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      # - ~/.zsh_history:/root/.zsh_history:z
      # Kubernetes
      # - ~/.kube:/root/.kube:z
    environment:
      - TZ=
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: zsh -c "while sleep 1000; do :; done"
    ports:
      - 3000/tcp